import { pageMetadata } from '../lib/metadata';
import Link from 'next/link';
import { Button, CTA, Eyebrow, SiteShell } from '../components';
import { categories, money, plansFor, solutions } from '../lib/solutions';

export const metadata = pageMetadata('Soluções', 'Sites, marketing, atendimento, CRM e inteligência artificial. Conheça as soluções FELIX e compare as três faixas de cada oferta.', '/solucoes');
export default function SolutionsPage() {
  return <SiteShell><main id="conteudo"><section className="page-intro"><div className="container"><Eyebrow>Soluções FELIX</Eyebrow><h1>Encontre a conexão<br /><span>que falta no seu negócio.</span></h1><div className="intro-bottom"><p>Da presença digital à operação comercial. Cada solução tem seu escopo, suas condições e três faixas para comparar.</p><Button href="/contato" secondary>Preciso de orientação</Button></div><nav className="category-navigation" aria-label="Categorias de soluções">{categories.map((category) => <a href={`#${category.id}`} key={category.id}>{category.name}<span aria-hidden="true">↓</span></a>)}</nav></div></section>{categories.map((category) => <section className="section catalog-section" id={category.id} key={category.id}><div className="container"><div className="section-heading"><div><Eyebrow>{category.name}</Eyebrow><h2>{category.description}</h2></div></div><div className="catalog-grid">{solutions.filter((solution) => solution.category === category.id).map((solution) => { const first = plansFor(solution.item)[0]; return <Link className={`catalog-item catalog-${solution.visual}`} href={`/solucoes/${solution.slug}`} key={solution.slug}><div className="catalog-top"><span className="tiny-label">{solution.number} / {solution.category === 'sistemas' ? 'SISTEMAS & IA' : category.name.toUpperCase()}</span><span aria-hidden="true">↗</span></div><div>{solution.mvp && <span className="mvp-label">MVP · PRÉ-VENDA</span>}<h3>{solution.name}</h3><p>{solution.description}</p></div><span className="catalog-price">Faixas desde <strong>{money(first.preco)}</strong>{first.periodicidade === 'mensal' ? '/mês' : ' por projeto'}<small>{first.implantacao ? '+ implantação · conheça o escopo' : 'Conheça o escopo e as condições'}</small></span></Link>; })}</div></div></section>)}<CTA title="Não sabe por onde começar?" body="Conte como seu negócio funciona hoje. A conversa começa pelo seu contexto." /></main></SiteShell>;
}
