import Link from 'next/link';
import { CTA, Eyebrow, ProjectGrid, SiteShell, SolutionGrid } from './components';

export default function Home() {
  return <SiteShell><main id="conteudo">
    <section className="lp-hero">
      <div className="lp-hero-signal" aria-hidden="true" />
      <div className="container lp-hero-shell">
        <div className="lp-hero-meta"><p className="hero-context">FELIX · SITES · SYSTEMS · AI</p><span>ESTRATÉGIA / COMUNICAÇÃO / TECNOLOGIA</span></div>
        <h1 aria-label="Sites que transformam interesse em contato."><span>SITES QUE</span><span><em>transformam</em></span><span>INTERESSE EM CONTATO.</span></h1>
        <div className="lp-hero-bottom"><p>Sites que vendem. Sistemas que operam. IA que escala. Infraestrutura digital para empresas venderem e operarem melhor.</p><div className="lp-hero-actions"><Link className="button lp-hero-primary" href="/solucoes">Conhecer as soluções <span aria-hidden="true">↗</span></Link><Link className="lp-hero-link" href="/projetos">Ver projetos <span aria-hidden="true">↓</span></Link></div></div>
      </div>
    </section>
    <div className="brand-strip"><div className="container"><span>AQUISIÇÃO</span><i aria-hidden="true" /><span>CONVERSÃO</span><i aria-hidden="true" /><span>OPERAÇÃO</span><i aria-hidden="true" /><span>SITES · SYSTEMS · AI</span></div></div>
    <section className="section company-section" id="empresa"><div className="container company-layout"><div><Eyebrow>A FELIX</Eyebrow><h2>Uma visão do negócio.<br />Da presença à operação.</h2></div><div className="company-copy"><p className="lead">Um site abre a conversa. O atendimento dá continuidade. O sistema organiza o que vem depois.</p><p>A FELIX conecta essas etapas com sites, marketing, sistemas e inteligência artificial. A atuação parte do seu contexto: como o cliente encontra você, como é atendido e como a oportunidade segue.</p><p>De Cascavel, no Paraná, para clínicas, profissionais liberais e empresas de serviços. Projetos digitais e produtos que podem atender negócios em qualquer cidade.</p></div></div><div className="container purpose-line"><span className="tiny-label">O QUE NOS MOVE</span><p>Conectar presença, atendimento e operação para o seu negócio <strong>vender e operar melhor.</strong></p></div></section>
    <section className="section solutions-section" id="solucoes"><div className="container"><div className="section-heading"><div><Eyebrow>O que podemos conectar</Eyebrow><h2>O objetivo é seu.<br />A solução começa por ele.</h2></div><Link className="text-link" href="/solucoes">Explorar as soluções <span aria-hidden="true">↗</span></Link></div><SolutionGrid compact /></div></section>
    <section className="section process-section" id="como-trabalhamos"><div className="container"><div className="section-heading"><div><Eyebrow>Como trabalhamos</Eyebrow><h2>Clareza antes.<br />Construção depois.</h2></div><p>O escopo e as condições são definidos para cada solução. Você sabe o que está contratando antes de começar.</p></div><div className="process-grid">{[['01', 'Entender', 'Seu negócio, o público e o que precisa funcionar melhor.'], ['02', 'Definir', 'A solução, as entregas e os limites do projeto.'], ['03', 'Construir', 'Mensagem, design e tecnologia conforme o escopo.'], ['04', 'Validar', 'Revisão e implantação. Acompanhamento conforme a contratação.']].map(([number, title, body]) => <article key={number}><span className="process-number">{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="section founder-section" id="fundador"><div className="container founder-layout"><div className="founder-name"><Eyebrow>Quem está por trás</Eyebrow><h2>Matheus<br /><span>Felix.</span></h2><div className="founder-caption"><span>FUNDADOR DA FELIX</span><span>CASCAVEL / PR</span></div></div><div className="founder-copy"><span className="tiny-label">ESTRATÉGIA, COMUNICAÇÃO E TECNOLOGIA</span><h3>IA aplicada ao marketing.<br />Visão de negócio na construção.</h3><p>Matheus Felix é especialista em IA aplicada ao Marketing, com atuação em automação comercial, produtos digitais e sistemas de aquisição e atendimento.</p><p>Desenha sistemas comerciais para clínicas e profissionais liberais, conectando site, conteúdo e atendimento com IA. Usa agentes de IA na produção e orienta as entregas pelas regras de cada área.</p><a className="text-link" href="https://www.linkedin.com/in/mhfelix95" target="_blank" rel="noopener noreferrer">Conhecer o perfil profissional <span aria-hidden="true">↗</span></a></div></div></section>
    <section className="section projects-section"><div className="container"><div className="section-heading"><div><Eyebrow>Aplicações reais</Eyebrow><h2>O trabalho ganha forma.</h2></div><Link className="text-link" href="/projetos">Conhecer os projetos <span aria-hidden="true">↗</span></Link></div><ProjectGrid preview /></div></section>
    <CTA />
  </main></SiteShell>;
}
