import Link from 'next/link';
import { Button, CTA, Eyebrow, ProjectGrid, SiteShell, SolutionGrid, XMark } from './components';

export default function Home() {
  return <SiteShell><main id="conteudo">
    <section className="home-hero"><div className="container hero-layout"><div className="hero-copy"><Eyebrow>FELIX · Sites · Systems · AI</Eyebrow><h1>Seu negócio.<br /><span>Mais conectado.</span></h1><p className="hero-description">Infraestrutura digital para empresas venderem e operarem melhor.</p><div className="hero-actions"><Button href="/solucoes">Conhecer as soluções</Button><Link className="text-link" href="#empresa">Conheça a FELIX <span aria-hidden="true">↓</span></Link></div><div className="hero-signature"><span>Sites que vendem.</span><span>Sistemas que operam.</span><span>IA que escala.</span></div></div><div className="connection-map" role="img" aria-label="A FELIX conecta aquisição, conversão e operação: sites, atendimento e sistemas."><span className="map-caption tiny-label">O NEGÓCIO NO CENTRO. TUDO EM CONEXÃO.</span><div className="map-ring ring-one" /><div className="map-ring ring-two" /><div className="map-line map-line-h" /><div className="map-line map-line-v" /><div className="map-core"><XMark /></div><div className="map-node node-acquisition"><span>01 / AQUISIÇÃO</span><strong>Sua mensagem.</strong><small>Sites · Conteúdo · Campanhas</small></div><div className="map-node node-conversion"><span>02 / CONVERSÃO</span><strong>A conversa certa.</strong><small>Atendimento · Qualificação</small></div><div className="map-node node-operation"><span>03 / OPERAÇÃO</span><strong>O próximo passo.</strong><small>CRM · Sistemas · IA</small></div><span className="map-foot tiny-label">ESTRATÉGIA + COMUNICAÇÃO + TECNOLOGIA</span></div></div></section>
    <div className="brand-strip"><div className="container"><span>Aquisição</span><span aria-hidden="true">↗</span><span>Conversão</span><span aria-hidden="true">↗</span><span>Operação</span><XMark /></div></div>
    <section className="section company-section" id="empresa"><div className="container company-layout"><div><Eyebrow>A FELIX</Eyebrow><h2>Uma visão do negócio.<br />Da presença à operação.</h2></div><div className="company-copy"><p className="lead">Um site abre a conversa. O atendimento dá continuidade. O sistema organiza o que vem depois.</p><p>A FELIX conecta essas etapas com sites, marketing, sistemas e inteligência artificial. A atuação parte do seu contexto: como o cliente encontra você, como é atendido e como a oportunidade segue.</p><p>De Cascavel, no Paraná, para clínicas, profissionais liberais e empresas de serviços. Projetos digitais e produtos que podem atender negócios em qualquer cidade.</p></div></div><div className="container purpose-line"><span className="tiny-label">O QUE NOS MOVE</span><p>Conectar presença, atendimento e operação para o seu negócio <strong>vender e operar melhor.</strong></p></div></section>
    <section className="section solutions-section" id="solucoes"><div className="container"><div className="section-heading"><div><Eyebrow>O que podemos conectar</Eyebrow><h2>O objetivo é seu.<br />A solução começa por ele.</h2></div><Link className="text-link" href="/solucoes">Explorar as soluções <span aria-hidden="true">↗</span></Link></div><SolutionGrid compact /></div></section>
    <section className="section process-section" id="como-trabalhamos"><div className="container"><div className="section-heading"><div><Eyebrow>Como trabalhamos</Eyebrow><h2>Clareza antes.<br />Construção depois.</h2></div><p>O escopo e as condições são definidos para cada solução. Você sabe o que está contratando antes de começar.</p></div><div className="process-grid">{[['01', 'Entender', 'Seu negócio, o público e o que precisa funcionar melhor.'], ['02', 'Definir', 'A solução, as entregas e os limites do projeto.'], ['03', 'Construir', 'Mensagem, design e tecnologia conforme o escopo.'], ['04', 'Validar', 'Revisão e implantação. Acompanhamento conforme a contratação.']].map(([number, title, body]) => <article key={number}><span className="process-number">{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="section founder-section" id="fundador"><div className="container founder-layout"><div className="founder-name"><Eyebrow>Quem está por trás</Eyebrow><h2>Matheus<br /><span>Felix.</span></h2><div className="founder-caption"><span>FUNDADOR DA FELIX</span><span>CASCAVEL / PR</span></div></div><div className="founder-copy"><span className="tiny-label">ESTRATÉGIA, COMUNICAÇÃO E TECNOLOGIA</span><h3>IA aplicada ao marketing.<br />Visão de negócio na construção.</h3><p>Matheus Felix é especialista em IA aplicada ao Marketing, com atuação em automação comercial, produtos digitais e sistemas de aquisição e atendimento.</p><p>Desenha sistemas comerciais para clínicas e profissionais liberais, conectando site, conteúdo e atendimento com IA. Usa agentes de IA na produção e orienta as entregas pelas regras de cada área.</p><a className="text-link" href="https://www.linkedin.com/in/mhfelix95" target="_blank" rel="noopener noreferrer">Conhecer o perfil profissional <span aria-hidden="true">↗</span></a></div></div></section>
    <section className="section projects-section"><div className="container"><div className="section-heading"><div><Eyebrow>Aplicações reais</Eyebrow><h2>O trabalho ganha forma.</h2></div><Link className="text-link" href="/projetos">Conhecer os projetos <span aria-hidden="true">↗</span></Link></div><ProjectGrid preview /></div></section>
    <CTA />
  </main></SiteShell>;
}
