import Link from 'next/link';
import { Eyebrow } from './components';
import { money, plansFor, titleCase, type Solution } from './lib/solutions';

export function Plans({ solution }: { solution: Solution }) {
  const plans = plansFor(solution.item);
  const notes = [...new Set(plans.flatMap((plan) => plan.observacoes.split('\n').map((line) => line.replace(/^\s*-\s*/, '').replaceAll('**', '').trim()).filter(Boolean)))];
  return <section className="section plans-section" id="planos"><div className="container"><div className="section-heading"><div><Eyebrow>{solution.mvp ? 'Faixas da pré-venda' : 'Escopo e investimento'}</Eyebrow><h2>Três faixas.<br />Escolha pelo que precisa.</h2></div><p>{solution.mvp ? 'Valores de tabela. A disponibilidade e as condições de cliente fundador são confirmadas na conversa.' : 'Compare entregas, limites e condições. A faixa intermediária é a recomendada do catálogo FELIX.'}</p></div><div className="plans-grid">{plans.map((plan, index) => <article className={`plan ${index === 1 ? 'plan-recommended' : ''}`} key={plan.id}><div className="plan-label"><span>{index === 1 ? 'RECOMENDADO' : index === 0 ? 'PARA COMEÇAR' : 'PARA AMPLIAR'}</span><span>0{index + 1}</span></div><h3>{titleCase(plan.faixa)}</h3><div className="plan-price">{plan.a_partir_de && <span className="price-prefix">A partir de</span>}<strong>{money(plan.preco)}</strong><span>{plan.periodicidade === 'mensal' ? '/ mês' : 'projeto · pagamento único'}</span></div><div className="plan-setup">{plan.implantacao ? <>Implantação: <strong>{money(plan.implantacao)}</strong></> : solution.item === 'felix-radar' || solution.item === 'trafego-pago' ? 'Sem taxa de implantação' : plan.periodicidade === 'mensal' ? 'Contratação mensal' : '50% na entrada · 50% na entrega'}</div><Link className={`button ${index === 1 ? '' : 'button-ghost'}`} href={`/contato?solucao=${solution.slug}&plano=${plan.faixa}`}>{solution.mvp ? 'Consultar pré-venda' : 'Conversar sobre esta faixa'}<span aria-hidden="true">↗</span></Link><dl className="plan-details">{Object.entries(plan.escopo).map(([key, value]) => value && <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}{Object.entries(plan.limites).map(([key, value]) => value && <div className="plan-limit" key={key}><dt>{key}</dt><dd>{key === 'Verba máxima' ? money(Number(value) * 100) : value}</dd></div>)}{plan.prazo_dias_uteis && <div className="plan-limit"><dt>Prazo</dt><dd>{plan.prazo_dias_uteis} dias úteis*</dd></div>}{plan.revisoes && <div className="plan-limit"><dt>Revisões</dt><dd>{plan.revisoes} rodadas</dd></div>}</dl></article>)}</div><div className="plan-notes"><h3>O que considerar na contratação</h3><ul>{notes.map((note) => <li key={note}>{note}</li>)}</ul>{plans.some((plan) => plan.prazo_dias_uteis) && <p>*O prazo começa após o recebimento do briefing e dos materiais.</p>}</div></div></section>;
}
